src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @Vich\Uploadable()
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 */
class Property
{
    const HEAT = [
        0 => "Électrique",
        1 => "Gaz"
    ];

    public function __construct()
    {
        $this->created_at = new \DateTime("now", new \DateTimeZone("Europe/Paris"));
        $this->options = new ArrayCollection();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $sold;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @Assert\Image(mimeTypes="image/jpeg")
     *
     * @Vich\UploadableField(mapping="properties", fileNameProperty="imageName")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(){
        return (new Slugify())->slugify($this->title);
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    /**
     * @return string|void
     */
    public function getFormatedPrice(){
        return number_format($this->price,0,""," ");
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getHeatType(){
        return self::HEAT[$this->getHeat()];
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(?bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Property
     */
    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;
        if($this->imageFile instanceof UploadedFile){
            $this->updated_at = new \DateTime("now");
        }
        return $this;
    }

    /**
     * @return string|null
     */
    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    /**
     * @param string|null $imageName
     * @return Property
     */
    public function setImageName(?string $imageName): Property
    {
        $this->imageName = $imageName;
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }


}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('surface')
            ->add('price')
            ->add('rooms')
            ->add('bedrooms')
            ->add('heat', ChoiceType::class, [
                "choices" => $this->getChoices(),
                "expanded" => true
            ])
            ->add('floor')
            ->add('adress')
            ->add('city')
            ->add('postal_code')
            ->add('sold')
            ->add('description')
            ->add("options",EntityType::class, [
                "class" => Option::class,
                "choice_label" => "name",
                "multiple" => true,
                "expanded" => true,
                "required" => false
            ])
            ->add("imageFile",FileType::class, [
                "required" => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            "translation_domain" => "form"
        ]);
    }

    private function getChoices(){
        $heats = Property::HEAT;
        $output = [];
        foreach($heats as $k => $v){
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php
namespace App\Controller;


use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController{

    /**
     * @var PropertyRepository
     */
    private $repository;
    /**
     * @var EntityManagerInterface
     */
    private $manager;

    public function __construct(PropertyRepository $repository,EntityManagerInterface $manager)
    {
        $this->repository = $repository;
        $this->manager = $manager;
    }

    /**
     * @Route("/biens", name="property.index")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @param $slug
     * @return Response
     */
    public function index(PaginatorInterface $paginator,Request $request):Response{

        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $propertiesQuery = $this->repository->findAllUnsolved($search);
        $properties = $paginator->paginate(
            $propertiesQuery,
            $request->query->getInt("pouge",1),
            12
        );

        return $this->render("property/index.html.twig",[
            "current_page" => "properties",
            "properties" => $properties,
            "form" => $form->createView()
        ]);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9-]*"})
     * @param Property $property
     * @param Request $request
     * @param $slug
     * @param ContactNotification $notification
     * @return Response
     */
    public function show(Property $property, Request $request, $slug,ContactNotification $notification){
        if($property->getSlug() !== $slug){
            return $this->redirectToRoute("property.show",[
                "id" => $property->getId(),
                "slug" => $property->getSlug()
            ],301);
        }

        $contact = new Contact();
        $contact->setProperty($property);
        $formContact = $this->createForm(ContactType::class,$contact);

        $formContact->handleRequest($request);
        if($formContact->isSubmitted() && $formContact->isValid()){
            $notification->notify($contact);
            $this->addFlash("success", "Votre message a été envoyé avec succès !");

            return $this->redirectToRoute("property.show",[
                "id" => $property->getId(),
                "slug" => $property->getSlug()
            ]);

        }

        return $this->render("property/show.html.twig",[
            "property"     => $property,
            "current_page" => "properties",
            "form"         => $formContact->createView()
        ]);
    }
}

templates/property/_property.html.twig
<div class="col-md-3 mb-4">
    <div class="card">
        {% if property.imageName %}
            <img src="{{ vich_uploader_asset(property,"imageFile") | imagine_filter("thumb") }}" alt="" class="card-img-top">
        {% else %}
            <img src="{{ "images/properties/empty.jpg" | imagine_filter("thumb") }}" alt="" class="card-img-top" >
        {% endif %}

        <div class="card-body">
            <h5 class="card-title"><a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">{{ property.title }}</a></h5>
            <p class="card-text">{{ property.city }} - {{ property.postalCode }}</p>
            <p class="card-text">Surface - {{ property.surface }}m²</p>
            <div style="font-size: 2rem;" class="text-primary">{{ property.formatedPrice }} €</div>
        </div>
    </div>
</div>

templates/property/index.html.twig
{% extends "base.html.twig" %}
{% block title %}Les biens proposés{% endblock %}


{% block body %}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="row align-items-end">
                <div class="col-md-5">
                    <div class="form-group">
                        {{ form_row(form.maxPrice) }}
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="form-group">
                        {{ form_row(form.minSurface) }}
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <button class="btn btn-primary">Rechercher</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="container">
        <h1 class="text-center">Les biens qu'on vous propose</h1>
        <div class="row">
            {% for property in properties %}
                {{ include('property/_property.html.twig') }}
            {% endfor %}

            <div class="mx-auto">
                {{ knp_pagination_render(properties) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/property/show.html.twig
{% extends "base.html.twig" %}
{% block title %}Ma super Agence !{% endblock %}


{% block body %}
    <div class="jumbotron">
        <div class="container">
            {% for message in app.flashes("success") %}
                <div class="alert alert-success text-center">{{ message }}</div>
            {% endfor %}
            {% if not form.vars.valid %}
                <div class="alert alert-danger">Les informations ne sont pas correctes</div>
            {% endif %}
            <div class="row">
                <div class="col-md-8">
                    {% if property.imageName %}
                        <img src="{{ vich_uploader_asset(property,"imageFile") | imagine_filter("medium") }}" alt="" class="img-fluid">
                    {% else %}
                        <img src="{{ "images/properties/empty.jpg" | imagine_filter("medium") }}" alt="" class="img-fluid">
                    {% endif %}
                </div>
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} pièces - {{ property.surface }}m²</h2>
                    <p style="font-size: 2rem;" class="text-primary">{{ property.formatedPrice }} €</p>
                    <button class="btn btn-primary">Contactez l'agence</button>
                    <div id="contactForm" class="mt-4">
                        {{ form_start(form) }}
                            <div class="row">
                                <div class="col">{{ form_row(form.firstname) }}</div>
                                <div class="col">{{ form_row(form.lastname) }}</div>
                            </div>
                        <div class="row">
                            <div class="col">{{ form_row(form.phone) }}</div>
                            <div class="col">{{ form_row(form.email) }}</div>
                        </div>
                        {{ form_rest(form) }}
                        <div class="form-group">
                            <button class="btn btn-primary">Envoyer</button>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <p>{{ property.description }}</p>
        <div class="row">
            <div class="col-md-8">
                <table class="table table-striped table-dark">
                    <tr>
                        <td>Surface</td>
                        <td>{{ property.surface }}m²</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Étage</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h4 class="text-center">Spécificités</h4>
                <ul class="list-group">
                    {% for option in property.options %}
                        <li class="list-group-item">{{ option.name }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}